# Site settings
title: Ed Gervais
email: e.a.gervais7@gmail.com
description: "I am a full stack web developer in the greater Seattle area with a passion for the outdoors, travel and family. I am excited to continually learn new code languages and make user friendly, helpful, and efficient web applications. When I am not coding you can find me out backpacking in the mountains around Washington and spending time with my family."
baseurl: ""
url: "http://www.edgervais.com"
twitter_username: egervais7
github_username: egervais7
linkedin_username: in/eagervais
facebook_username: edd.on.trails

# Build settings
markdown: kramdown
